import React,{useState} from 'react';
import {penaltyReasons} from './penalty-reasons.js';
import {useI18n} from './i18n.js';
import {formatTime,parseTime} from './clock.js';
import {PRESETS_KEY,presetSettings} from './management.js';
const localInput=ms=>{if(ms==null)return '';const d=new Date(ms);return new Date(ms-d.getTimezoneOffset()*60000).toISOString().slice(0,19);};
export function EventEditor({event,save,close,Frame}){
 const t=useI18n();const [draft,setDraft]=useState({...event,up:event.elapsedMs==null?'':formatTime(Math.floor(event.elapsedMs/1000)*1000),down:formatTime(event.remainingMs),local:localInput(event.occurredAt),assist1:event.assists?.[0]||'',assist2:event.assists?.[1]||''});const [error,setError]=useState('');const change=(key,value)=>setDraft(old=>({...old,[key]:value}));
 return <Frame title={t('Edit event')} close={close}><form onSubmit={e=>{e.preventDefault();const remainingMs=parseTime(draft.down),elapsedMs=draft.up?parseTime(draft.up):null,occurredAt=draft.local?new Date(draft.local).getTime():null;const players=[draft.scorer,draft.assist1,draft.assist2].map(value=>(value||'').trim()).filter(Boolean);if(remainingMs==null||(draft.up&&elapsedMs==null)||(draft.local&&!Number.isFinite(occurredAt))){setError('Check the event times.');return;}if(new Set(players).size!==players.length){setError('Scorer and assists must be different players.');return;}save({period:Number(draft.period),remainingMs,elapsedMs,occurredAt,scorer:(draft.scorer||'').trim(),assists:[draft.assist1,draft.assist2].map(value=>value.trim()).filter(Boolean),player:(draft.player||'').trim(),reason:draft.reason||''});}}>
 <p>{t('Edits correct the match sheet and goal details. Live scores, clocks and penalties stay under operator control.')}</p><label>{t('Period')}<input type="number" min="1" max="99" required value={draft.period} onChange={e=>change('period',e.target.value)}/></label><div className="form-grid">{[['up','Elapsed clock'],['down','Remaining clock']].map(([key,label])=><label key={key}>{t(label)}<input required={key==='down'} value={draft[key]} placeholder="MM:SS" onChange={e=>change(key,e.target.value)}/></label>)}</div><label>{t('Local time')}<input type="datetime-local" step="1" value={draft.local} onChange={e=>change('local',e.target.value)}/></label>
 {event.type==='Goal'&&<><label>{t('Scorer')}<input maxLength="8" value={draft.scorer||''} onChange={e=>change('scorer',e.target.value)}/></label><div className="form-grid">{[['assist1','Assist 1 (optional)'],['assist2','Assist 2 (optional)']].map(([key,label])=><label key={key}>{t(label)}<input maxLength="8" value={draft[key]} onChange={e=>change(key,e.target.value)}/></label>)}</div></>}{event.type.startsWith('Penalty')&&<label>{t('Penalty reason (optional)')}<select value={draft.reason||''} onChange={e=>change('reason',e.target.value)}><option value="">{t('Not specified')}</option>{penaltyReasons.map(item=><option key={item.id} value={item.id}>{t(item.label)}</option>)}</select></label>}{event.player!=null&&<label>{t('Player number (optional)')}<input maxLength="8" value={draft.player} onChange={e=>change('player',e.target.value)}/></label>}
 {error&&<p className="form-error">{t(error)}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>{t('Cancel')}</button><button className="primary">{t('Save event')}</button></div></form></Frame>;
}
export function PresetManager({settings,apply,close,Frame}){
 const t=useI18n();const [rows,setRows]=useState(()=>{try{const data=JSON.parse(localStorage.getItem(PRESETS_KEY)||'[]');return Array.isArray(data)?data.filter(r=>typeof r.name==='string'&&r.settings):[];}catch{return [];}});const [name,setName]=useState('');const [error,setError]=useState('');
 const store=next=>{try{localStorage.setItem(PRESETS_KEY,JSON.stringify(next));setRows(next);setError('');return true;}catch{setError('Changes could not be saved on this device.');return false;}};
 return <Frame title={t('Match presets')} close={close}><p>{t('Save current period, break and horn settings. Applying a preset keeps the current score and clock; period length applies to the next period or a new game.')}</p><form onSubmit={e=>{e.preventDefault();if(!name.trim())return;if(store([...rows,{id:crypto.randomUUID(),name:name.trim(),settings:presetSettings(settings)}]))setName('');}}><label>{t('Preset name')}<input required maxLength="60" value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary">{t('Save current settings')}</button></form><div className="preset-list">{rows.map(row=><div key={row.id}><strong>{row.name}</strong><button className="secondary" onClick={()=>apply(row.settings)}>{t('Apply')}</button><button className="secondary" onClick={()=>store(rows.filter(r=>r.id!==row.id))}>{t('Delete')}</button></div>)}</div>{error&&<p className="form-error">{t(error)}</p>}</Frame>;
}
