import React, {useState, useRef, useEffect, useMemo} from 'react';
import {penaltyReasonLabel} from './penalty-reasons.js';
import Icon from './Icon.jsx';
import {downloadCsv} from './management.js';
import {translator} from './i18n.js';
import {formatTime} from './clock.js';
import {teamDisplayName} from './youth.js';
import {reportModel,reviewIssues,matchElapsed,elapsedTime,localTime,backupText,readBackup,downloadFile,reportCsv} from './match-report.js';

function Table({headers,children,className=''}) {
  return <div className={`report-table-wrap ${className}`}><table><thead><tr>{headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
}
export default function MatchSheet({game,toolbar,toggleClock,editEvent,addNote,saveInfo,restoreBackup,getSnapshot,goBoard}) {
  const t=translator(game.settings.language), teamName=team=>teamDisplayName(game.settings,team,t);
  const [view,setView]=useState('events'),[period,setPeriod]=useState(''),[journal,setJournal]=useState(false);
  const [incoming,setIncoming]=useState(null),[error,setError]=useState('');
  const file=useRef(null),content=useRef(null);
  useEffect(()=>{if(content.current)content.current.scrollTop=0;},[view,period]);
  const fullReport=useMemo(()=>reportModel(game),[game.events,game.goals,game.period]);
  const report=useMemo(()=>reportModel(game,period),[game.events,game.goals,game.period,period]);
  const issues=useMemo(()=>reviewIssues(game),[game.events,game.goals,game.scores,game.period,game.periodLengths]);
  const grouped=new Map();
  issues.forEach(issue=>{const key=issue.event?.id||issue.id;if(!grouped.has(key))grouped.set(key,{...issue,messages:[]});grouped.get(key).messages.push(issue.message);});
  const activeGoalIds=new Set(fullReport.goals.map(e=>e.id));
  const events=game.events.filter(e=>(!period||e.period===Number(period))&&(journal||['Goal','Penalty added','Timeout started','Match note'].includes(e.type))).slice().reverse();
  const editButton=e=><button className="board-button" onClick={()=>editEvent(e)}><Icon name="settings"/>{t('Edit')}</button>;
  const importFile=async e=>{
    const picked=e.target.files?.[0];e.target.value='';if(!picked)return;
    if(picked.size>15*1024*1024){setError('Invalid match backup.');return;}
    try {const restored=readBackup(await picked.text());if(!restored)throw Error();setIncoming(restored);setError('');}catch{setError('Invalid match backup.');}
  };
  return <section className="scoreboard match-sheet"><div className="board-admin-tools">{toolbar}</div>
    <div className="sheet-heading"><div><h1>{t('Match sheet')}</h1><h2 className="sheet-score">{teamName('home')} <b>{game.scores.home} — {game.scores.away}</b> {teamName('away')}</h2></div><button className="board-button" onClick={toggleClock}><Icon name={(game.auxiliary?.running??game.running)?'pause':'play'}/>{t((game.auxiliary?.running??game.running)?'Pause game':'Resume / start')} · {formatTime(game.auxiliary?.remainingMs??game.remainingMs)}</button></div>
    <div className="sheet-navigation no-print"><nav aria-label={t('Match sheet')} className="board-tabs">{[['events','Events'],['review','To complete'],['report','Preview / export']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{t(label)}{id==='review'&&grouped.size>0&&<span className="sheet-count">{grouped.size}</span>}</button>)}</nav><label className="period-filter">{t('Period')}<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="">{t('All periods')}</option>{report.periods.map(p=><option key={p} value={p}>{t('Period')} {p}</option>)}</select></label></div>
    <div className="sheet-content" ref={content}>
      {view==='events'&&<div className="no-print"><div className="sheet-section-tools"><label className="check-label"><input type="checkbox" checked={journal} onChange={e=>setJournal(e.target.checked)}/>{t('Full journal')}</label>{journal&&<button className="board-button" onClick={()=>downloadCsv(game)}>{t('Export journal')}</button>}<button className="board-button" onClick={addNote}><Icon name="sheet"/>{t('Note +')}</button></div>{!events.length?<p className="sheet-empty">{t('No match events yet.')}</p>:<Table className="event-table" headers={['Event','Team / players','Elapsed clock','Remaining clock','Local time','Edit'].map(t)}>{events.map(e=><tr key={e.id} className={e.type==='Goal'&&!activeGoalIds.has(e.id)?'event-cancelled':''}><td><strong>{t(e.type)}</strong><small>{t('Period')} {e.period}{e.type==='Goal'&&!activeGoalIds.has(e.id)?` · ${t('Cancelled')}`:''}</small>{e.label&&<small>{e.label} · {t(penaltyReasonLabel(e.reason))}</small>}{e.note&&<small className="internal-note">{e.note}</small>}{e.editedAt&&<small>{t('Corrected')}</small>}</td><td>{e.team&&teamName(e.team)}{(e.scorer||e.player)&&<small>#{e.scorer||e.player}</small>}{e.assists?.length>0&&<small>{t('Assists')} : {e.assists.join(' · ')}</small>}{e.servedBy&&<small>{t('Served by')}: #{e.servedBy}</small>}</td><td data-label={t('Elapsed clock')}>{elapsedTime(e.elapsedMs)}</td><td data-label={t('Remaining clock')}>{formatTime(e.remainingMs)}</td><td data-label={t('Local time')}>{localTime(e,game)}</td><td>{editButton(e)}</td></tr>)}</Table>}<p className="sheet-help">{t('Notes are internal and excluded from the report. Times here refer to the current period.')}</p></div>}
      {view==='review'&&<div className="review-list no-print"><p className="sheet-help">{t('Complete what you know. You can export with fields left blank.')}</p>{[...grouped.values()].filter(issue=>!period||!issue.event||issue.event.period===Number(period)).map(issue=><article className="review-item" key={issue.id}><div><strong>{issue.event?`${t(issue.event.type)} · ${t('Period')} ${issue.event.period} · ${formatTime(issue.event.remainingMs)}`:teamName(issue.team)}</strong>{issue.event?.team&&<small>{teamName(issue.event.team)} {issue.event.scorer||issue.event.player?`#${issue.event.scorer||issue.event.player}`:''}</small>}<p>{issue.messages.map(t).join(' · ')}</p></div>{issue.event?editButton(issue.event):<button className="board-button" onClick={goBoard}>{t('Check score')}</button>}</article>)}{!issues.some(issue=>!period||!issue.event||issue.event.period===Number(period))&&<p className="sheet-empty">{t('Nothing to complete in the recorded events.')}</p>}</div>}
      {view==='report'&&<>
        <div className="sheet-section-tools no-print"><p className="sheet-help">{t('Pre-filled aid. Complete and check against the official sheet.')}</p><div className="sheet-actions"><button className="board-button" onClick={()=>downloadFile(reportCsv(game,period,t,teamName),'icetracker-report.csv','text/csv;charset=utf-8')}>CSV</button><button className="board-button" onClick={()=>window.print()}><Icon name="sheet"/>{t('Print / PDF')}</button></div></div>
        <details className="sheet-disclosure no-print"><summary>{t('Match information')} <span>{t('Optional')}</span></summary><form className="match-info-form" onSubmit={e=>{e.preventDefault();saveInfo(Object.fromEntries(new FormData(e.currentTarget)));e.currentTarget.closest('details').open=false;}}><div className="form-grid">{[['date','Date','date'],['scheduledTime','Scheduled time','time'],['venue','Venue','text'],['competition','Competition','text'],['number','Match number','text']].map(([key,label,type])=><label key={key}>{t(label)}<input name={key} type={type} maxLength={100} defaultValue={game.matchInfo?.[key]||''}/></label>)}</div><button className="board-button">{t('Save')}</button></form></details>
        {issues.length>0&&<p className="report-caution">{t('Some entries need checking. Missing information stays blank.') } <button className="board-button no-print" onClick={()=>setView('review')}>{t('Review')} · {grouped.size}</button></p>}
        <div className="match-report"><div className="report-title"><h2>{t('Match transcription aid')}</h2><p>{period?`${t('Period')} ${period}`:t('All periods')}{game.matchInfo?.date?` · ${game.matchInfo.date}`:''}{game.matchInfo?.scheduledTime?` · ${game.matchInfo.scheduledTime}`:''}{game.matchInfo?.venue?` · ${game.matchInfo.venue}`:''}</p><p>{[game.matchInfo?.competition,game.matchInfo?.number].filter(Boolean).join(' · ')}</p></div>
        {['home','away'].map((team,index)=><section className="report-team" key={team}><h3>{index===0?'A':'B'} · {teamName(team)}</h3><h4>{t('Goals')}</h4><Table headers={['#','Period','Match elapsed','Scorer','Assists'].map(t)}>{report.goals.filter(e=>e.team===team).map((e)=><tr key={e.id}><td>{fullReport.goals.filter(g=>g.team===team).findIndex(g=>g.id===e.id)+1}</td><td>{e.period}</td><td>{elapsedTime(matchElapsed(game,e))}</td><td>{e.scorer||'—'}</td><td>{e.assists?.join(' / ')||'—'}</td></tr>)}</Table><h4>{t('Penalties')}</h4><Table headers={['Period','Match elapsed','Player','Assessed minutes','Reason','Start time','End'].map(t)}>{report.penalties.filter(e=>e.team===team).map(e=><tr key={e.id}><td>{e.period}</td><td>{elapsedTime(matchElapsed(game,e))}</td><td>{e.kind==='bench'?'E':e.player||'—'}{e.servedBy&&<small>{t('Served by')} {e.servedBy}</small>}</td><td>{e.durationMs==null?'—':Number((e.durationMs/60000).toFixed(2))}</td><td>{t(penaltyReasonLabel(e.reason))||'—'}</td><td>{elapsedTime(e.startMs)}</td><td>{elapsedTime(e.endMs)}</td></tr>)}</Table></section>)}
        <h3>{t('Period summary')}</h3><Table headers={['Period',`${t('Goals')} A / B`,`${t('Assessed minutes')} A / B`,'Start time','End'].map(t)}>{report.totals.map(row=><tr key={row.period}><td>{row.period}</td><td>{row.home.goals} / {row.away.goals}</td><td>{Number((row.home.penaltyMs/60000).toFixed(2))} / {Number((row.away.penaltyMs/60000).toFixed(2))}</td><td>{localTime(row.start,game)}</td><td>{localTime(row.end,game)}</td></tr>)}<tr><td><strong>{t('Total')}</strong></td><td>{report.goals.filter(e=>e.team==='home').length} / {report.goals.filter(e=>e.team==='away').length}</td><td>{['home','away'].map(team=>Number((report.penalties.filter(e=>e.team===team).reduce((sum,e)=>sum+(e.durationMs||0),0)/60000).toFixed(2))).join(' / ')}</td><td colSpan="2"/></tr></Table>
        <h3>{t('Timeouts')}</h3>{report.timeouts.length?report.timeouts.map(e=><p key={e.id}>{teamName(e.team)} · {elapsedTime(matchElapsed(game,e))}</p>):<p>—</p>}
        <p className="sheet-help">{t('Event times are cumulative match time. Start/end in the period summary are local times. Penalty totals use assessed minutes.')}</p><p className="sheet-help">{t('Rosters, officials, signatures and unrecorded statistics remain on the official sheet.')}</p><a className="no-print" href="https://www.hockeyfrance.com/wp-content/uploads/2020/09/FeuilledematchVierge.pdf" target="_blank" rel="noreferrer">{t('Open FFHG template')}</a>
        </div>
      </>}
      <details className="sheet-disclosure backup-disclosure no-print"><summary>{t('Save / recover match')}</summary><p className="sheet-help">{t('Saved automatically in this browser. Download a backup to keep the match or move it to another computer. Restores paused.')}</p><div className="sheet-actions"><button className="board-button" onClick={()=>downloadFile(backupText(getSnapshot()),'icetracker-match.json')}>{t('Download backup')}</button><button className="board-button" onClick={()=>file.current.click()}>{t('Open backup')}</button><input hidden ref={file} type="file" accept=".json,application/json" onChange={importFile}/></div>{error&&<p role="alert">{t(error)}</p>}{incoming&&<div className="import-confirm" role="region" aria-label={t('Open backup')}><strong>{incoming.settings.home} {incoming.scores.home} — {incoming.scores.away} {incoming.settings.away}</strong><p>{t('Period')} {incoming.period} · {formatTime(incoming.remainingMs)} · {incoming.events.length} {t('Events')}</p><p>{t('Replace the current match? Download its backup first if you want to keep it. Undo can restore it until your next action.')}</p><div className="sheet-actions"><button className="board-button" onClick={()=>setIncoming(null)}>{t('Cancel')}</button><button className="board-button" onClick={()=>{restoreBackup(incoming);setIncoming(null);setPeriod('');}}>{t('Replace and open')}</button></div></div>}</details>
    </div>
  </section>;
}
